variables:
  CI_IMAGE_TAG: 'opencl'
  package: 'CLBlast'

stages:
  - test
  #- postprocess

before_script:
  - apt-get update && apt-get install -y cmake clang

include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v0/common.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v0/test_v0.7.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v0/test_v1.0.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v0/test_dev.yml'
  #- 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v0/postprocess_coverage.yml'
  #- 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v0/postprocess_documentation.yml'

test:v0.6:
  stage: test
  image: "juliagpu/julia:v0.6-${CI_IMAGE_TAG}"
  script:
    - julia -e 'versioninfo()'
    - julia -e "Pkg.init();
                symlink(\"$CI_PROJECT_DIR\", Pkg.dir(\"$package\"));
                Pkg.resolve();
                Pkg.build(\"$package\");
                Pkg.test(\"$package\")"

test:v1.0:
  allow_failure: true

test:dev:
  allow_failure: true
