variables:
  CI_IMAGE_TAG: 'opencl'
  package: 'CLBlast'

stages:
  - test
  #- postprocess

before_script:
  - apt-get update && apt-get install -y cmake clang

include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/3fbe3d2dd7288b4c91e8b7b2fbbd98b9bdeeb92a/templates/v3/common.yml'
  #- 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v0/common.yml'
  #- 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v0/test_v0.7.yml'
  #- 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v0/test_v1.0.yml'
  #- 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v0/test_dev.yml'
  #- 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v0/postprocess_coverage.yml'
  #- 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v0/postprocess_documentation.yml'

nvidia:test:dev:
    extends: .test
    variables:
        CI_IMAGE_TAG: 'opencl'
        CI_VERSION_TAG: 'dev'
    tags:
        - cuda
    allow_failure: true

amd:test:dev:
    extends: .test
    variables:
        CI_IMAGE_TAG: 'rocm'
        CI_VERSION_TAG: 'dev'
    tags:
        - rocm
    allow_failure: true

nvidia:test:v1.3:
    extends: .test
    variables:
        CI_IMAGE_TAG: 'opencl'
        CI_VERSION_TAG: 'v1.3'
    tags:
        - cuda

amd:test:v1.3:
    extends: .test
    variables:
        CI_IMAGE_TAG: 'rocm'
        CI_VERSION_TAG: 'v1.3'
    tags:
        - rocm

