## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

julia:
  - 0.6
  - 0.7
  - 1.0
  - release
  - nightly

os:
#  - linux
  - osx

notifications:
  email: false

git:
  depth: 99999999

# uncomment the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: 0.7
  - julia: 1.0
  - julia: release
  - julia: nightly

# uncomment and modify the following lines to manually install system packages
addons:
  apt: # apt-get for linux
    packages:
    - clang
    - libclang-dev
    - llvm
    - llvm-dev
    - libltdl3-dev
    - libhwloc-dev
    - opencl-headers
    - ocl-icd-dev
    - ocl-icd-opencl-dev
before_script: # pocl
  - if [ $TRAVIS_OS_NAME = linux ]; then bash .travis_install_pocl.sh; fi
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

# uncomment the following lines to override the default test script
#script:
#  - julia --check-bounds=yes --color=yes -e 'if VERSION >= v"0.7.0-" using Pkg; end; Pkg.clone(pwd(), "CLBlast"); Pkg.build("CLBlast"); Pkg.test("CLBlast", coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'if VERSION >= v"0.7.0-" using Pkg; end; cd(Pkg.dir("CLBlast")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'if VERSION >= v"0.7.0-" using Pkg; end; cd(Pkg.dir("CLBlast")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
